### ISSUE TITLE
Normal speed button

### ISSUE THREAD

**Issue by sourcegr** [WebReflection/movit#1]
Definitely needs a "normal speed" button or something, the slider is so difficult to handle... ;)

**Comment by WebReflection** [comment]
How is a checkbox to disable it difficult to handle? When you disable it it goes back to normal speed.

**Comment by sourcegr** [comment]
OK, I will try to explain it a little bit more...

The way I see it is that there should be no "disable" at all - instead a  "normal" button should set the speed to "1" - this essentially achieves the same effect as "disable" but you still have the slider enabled to fiddle with it whenever you want.

Also, right now, if you click 'disable' the slider also gets disabled; but when you click enable again, the last setting is immediately applied to the speed.

**Comment by WebReflection** [comment]
Are you actually using this?

As extension, you want to be sure when disabled nothing happens at all.

If you were using this, you'd set 1.3 or similar, and use it whenever it's needed, disabling it any other time.

**Comment by sourcegr** [comment]
forget about it
